services:
  cassandra-seed:
    image: cassandra:4.1
    container_name: cassandra-seed
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=ShortenerCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    deploy:
      resources:
        limits:
          memory: 1024M

  cassandra-node:
    image: cassandra:4.1
    container_name: cassandra-node
    environment:
      - CASSANDRA_CLUSTER_NAME=ShortenerCluster
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    depends_on:
      - cassandra-seed
    deploy:
      resources:
        limits:
          memory: 1024M

  read-service:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - CASSANDRA_HOSTS=cassandra-seed,cassandra-node
      - CASSANDRA_KEYSPACE=url_shortener
      - BASE_URL=http://localhost:8000
    depends_on:
      - cassandra-seed
    command: uvicorn main_read:app --host 0.0.0.0 --port 8000

  write-service:
    build: .
    restart: always
    ports:
      - "8001:8000"
    environment:
      - CASSANDRA_HOSTS=cassandra-seed,cassandra-node
      - CASSANDRA_KEYSPACE=url_shortener
      - BASE_URL=http://localhost:8000
    depends_on:
      - cassandra-seed
    command: uvicorn main_write:app --host 0.0.0.0 --port 8000

  cleanup-service:
    build: .
    restart: always
    environment:
      - CASSANDRA_HOSTS=cassandra-seed,cassandra-node
      - CASSANDRA_KEYSPACE=url_shortener
      - CLEANUP_STRATEGY=created_at
      - CLEANUP_TTL_SECONDS=15
      - CLEANUP_INTERVAL_SECONDS=10
    depends_on:
      - cassandra-seed
    command: python main_cleanup.py

